version: '3'

services:
  web:
    build: .
    command: gunicorn djangoproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
    expose:
      - "8000"
  
  nginx:
    image: nginx:1.19
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

volumes:
  static_volume:
